### ISSUE TITLE
Nifi Template cannot be imported

### ISSUE THREAD

**Issue by peersbio** [anair-it/nifi-docker#1]
Hi,

I am working on a project to retrieve xml data from IBM MQ to Hdfs via Nifi.  I am very happy to find your example here.

However, I download the Nifi Template. When I tried to import the xml template to Nifi,  I got the error --- Unable to Upload The specified template is not in a valid format.  Could you verify if the template format is working?

Thanks a lot

Andy

**Comment by anair-it** [comment]
I'll update that and upload the correct one.

**Comment by anair-it** [comment]
I'm able to import the file and run the same UDP logger test.
